export const mockCourses = [
  {
    id: "1",
    title: "Khmer Language Fundamentals",
    description: "Master reading, writing, and grammar in Khmer language",
    educatorId: "1",
    educatorName: "Mrs. Sopheak",
    level: "Beginner",
    students: 156,
    lessons: 24,
    image: "/khmer-course.jpg",
    category: "Khmer",
  },
  {
    id: "2",
    title: "Chemistry Basics",
    description: "Explore atoms, molecules, chemical reactions, and the periodic table",
    educatorId: "2",
    educatorName: "Mr. Veasna",
    level: "Beginner",
    students: 89,
    lessons: 22,
    image: "/chemistry-course.jpg",
    category: "Chemistry",
  },
  {
    id: "3",
    title: "Physics Principles",
    description: "Learn mechanics, energy, waves, and fundamental physics concepts",
    educatorId: "3",
    educatorName: "Dr. Sok",
    level: "Intermediate",
    students: 102,
    lessons: 26,
    image: "/physics-course.jpg",
    category: "Physics",
  },
  {
    id: "4",
    title: "Mathematics Essentials",
    description: "Build strong foundation in algebra, geometry, and calculus",
    educatorId: "4",
    educatorName: "Ms. Dara",
    level: "Beginner",
    students: 145,
    lessons: 30,
    image: "/mathematics-course.jpg",
    category: "Mathematics",
  },
  {
    id: "5",
    title: "Advanced Chemistry",
    description: "Organic chemistry, thermodynamics, and chemical equilibrium",
    educatorId: "2",
    educatorName: "Mr. Veasna",
    level: "Advanced",
    students: 43,
    lessons: 20,
    image: "/chemistry-course.jpg",
    category: "Chemistry",
  },
  {
    id: "6",
    title: "Advanced Physics",
    description: "Quantum mechanics, relativity, and modern physics concepts",
    educatorId: "3",
    educatorName: "Dr. Sok",
    level: "Advanced",
    students: 38,
    lessons: 24,
    image: "/physics-course.jpg",
    category: "Physics",
  },
]

export const mockEnrollments = [
  {
    courseId: "1",
    studentId: "1",
    progress: 75,
    completed: false,
  },
  {
    courseId: "2",
    studentId: "1",
    progress: 60,
    completed: false,
  },
  {
    courseId: "4",
    studentId: "1",
    progress: 85,
    completed: false,
  },
]

export const mockAssignments = [
  {
    id: "1",
    courseId: "1",
    title: "Khmer Essay Writing",
    dueDate: "2025-01-20",
    points: 100,
    status: "pending",
  },
  {
    id: "2",
    courseId: "2",
    title: "Chemical Equations Practice",
    dueDate: "2025-01-25",
    points: 100,
    status: "submitted",
    grade: 92,
  },
  {
    id: "3",
    courseId: "4",
    title: "Calculus Problem Set",
    dueDate: "2025-01-28",
    points: 100,
    status: "pending",
  },
]

export const mockQuizzes = [
  {
    id: "1",
    courseId: "1",
    title: "Khmer Grammar Quiz",
    questions: 15,
    timeLimit: 30,
    passingScore: 70,
  },
  {
    id: "2",
    courseId: "2",
    title: "Periodic Table Quiz",
    questions: 20,
    timeLimit: 25,
    passingScore: 75,
  },
  {
    id: "3",
    courseId: "3",
    title: "Newton's Laws Quiz",
    questions: 12,
    timeLimit: 20,
    passingScore: 70,
  },
  {
    id: "4",
    courseId: "4",
    title: "Algebra Fundamentals Quiz",
    questions: 18,
    timeLimit: 35,
    passingScore: 75,
  },
]

export const mockLessons = [
  {
    id: "1",
    courseId: "1",
    title: "Introduction to Khmer Script",
    description: "Learn the basics of Khmer alphabet and pronunciation",
    videoUrl: "https://www.youtube.com/embed/Wwlv-PRXjuQ",
    order: 1,
  },
  {
    id: "2",
    courseId: "1",
    title: "Khmer Vowels and Consonants",
    description: "Master vowel and consonant combinations",
    videoUrl: "https://www.youtube.com/embed/DcWZR_aqWT4",
    order: 2,
  },
  {
    id: "3",
    courseId: "2",
    title: "Introduction to Chemistry",
    description: "What is chemistry and why it matters",
    videoUrl: "https://www.youtube.com/embed/t8x3wdXZGEY",
    order: 1,
  },
  {
    id: "4",
    courseId: "2",
    title: "Atomic Structure",
    description: "Understanding atoms, protons, neutrons, and electrons",
    videoUrl: "https://www.youtube.com/embed/TYEYEIuTmGQ",
    order: 2,
  },
  {
    id: "5",
    courseId: "3",
    title: "Introduction to Physics",
    description: "The study of matter, energy, and their interactions",
    videoUrl: "https://www.youtube.com/embed/b1t41Q3xRM8",
    order: 1,
  },
  {
    id: "6",
    courseId: "3",
    title: "Newton's First Law",
    description: "Objects in motion stay in motion",
    videoUrl: "https://www.youtube.com/embed/adLj6kygwds",
    order: 2,
  },
  {
    id: "7",
    courseId: "4",
    title: "Introduction to Algebra",
    description: "Variables, expressions, and equations",
    videoUrl: "https://www.youtube.com/embed/NybHckSEQBI",
    order: 1,
  },
  {
    id: "8",
    courseId: "4",
    title: "Solving Linear Equations",
    description: "Step-by-step guide to solving equations",
    videoUrl: "https://www.youtube.com/embed/7DPWeBszNSM",
    order: 2,
  },
]

export const mockUsers = [
  {
    id: "admin-1",
    email: "admin@komplex.edu",
    fullName: "Admin Komplex",
    role: "admin" as const,
    status: "active" as const,
    joinedDate: "2024-01-01",
  },
  {
    id: "educator-1",
    email: "sopheak@komplex.edu",
    fullName: "Mrs. Sopheak",
    role: "educator" as const,
    status: "active" as const,
    joinedDate: "2024-02-15",
    courses: 3,
  },
  {
    id: "educator-2",
    email: "veasna@komplex.edu",
    fullName: "Mr. Veasna",
    role: "educator" as const,
    status: "active" as const,
    joinedDate: "2024-03-10",
    courses: 2,
  },
  {
    id: "educator-3",
    email: "sok@komplex.edu",
    fullName: "Dr. Sok",
    role: "educator" as const,
    status: "pending" as const,
    joinedDate: "2024-12-01",
    courses: 0,
  },
  {
    id: "educator-4",
    email: "dara@komplex.edu",
    fullName: "Ms. Dara",
    role: "educator" as const,
    status: "active" as const,
    joinedDate: "2024-04-20",
    courses: 2,
  },
  {
    id: "student-1",
    email: "student1@komplex.edu",
    fullName: "Chanthy Sok",
    role: "student" as const,
    status: "active" as const,
    joinedDate: "2024-09-01",
    courses: 3,
  },
  {
    id: "student-2",
    email: "student2@komplex.edu",
    fullName: "Sokha Lim",
    role: "student" as const,
    status: "active" as const,
    joinedDate: "2024-09-05",
    courses: 2,
  },
  {
    id: "analyst-1",
    email: "analyst@komplex.edu",
    fullName: "Data Analyst",
    role: "analyst" as const,
    status: "active" as const,
    joinedDate: "2024-01-15",
  },
]

export const mockSystemStats = {
  totalUsers: 573,
  totalEducators: 45,
  totalStudents: 526,
  totalAnalysts: 2,
  totalCourses: 28,
  activeCourses: 24,
  totalEnrollments: 1842,
  pendingEducators: 3,
  totalQuizzes: 156,
  totalAssignments: 284,
  systemHealth: "excellent" as const,
}

export const mockUserGrowth = [
  { month: "Jul", users: 320, educators: 28, students: 290 },
  { month: "Aug", users: 385, educators: 32, students: 350 },
  { month: "Sep", users: 442, educators: 38, students: 400 },
  { month: "Oct", users: 498, educators: 41, students: 452 },
  { month: "Nov", users: 538, educators: 43, students: 490 },
  { month: "Dec", users: 573, educators: 45, students: 526 },
]

export const mockRecentActivity = [
  {
    id: "1",
    type: "enrollment" as const,
    user: "Chanthy Sok",
    action: "enrolled in Chemistry Basics",
    time: "2 minutes ago",
  },
  {
    id: "2",
    type: "submission" as const,
    user: "Sokha Lim",
    action: "submitted Algebra Fundamentals Quiz",
    time: "15 minutes ago",
  },
  {
    id: "3",
    type: "course" as const,
    user: "Mrs. Sopheak",
    action: "created new lesson in Khmer Language",
    time: "1 hour ago",
  },
  {
    id: "4",
    type: "registration" as const,
    user: "Dr. Sok",
    action: "registered as educator (pending approval)",
    time: "3 hours ago",
  },
  {
    id: "5",
    type: "quiz" as const,
    user: "Mr. Veasna",
    action: "created Chemistry Quiz",
    time: "5 hours ago",
  },
]

export const mockCourseStats = [
  { subject: "Mathematics", enrollments: 492, completion: 78 },
  { subject: "Khmer", enrollments: 385, completion: 82 },
  { subject: "Chemistry", enrollments: 356, completion: 71 },
  { subject: "Physics", enrollments: 329, completion: 68 },
]

export const mockQuizPerformance = [
  { subject: "Mathematics", avgScore: 82, attempts: 1245 },
  { subject: "Khmer", avgScore: 87, attempts: 956 },
  { subject: "Chemistry", avgScore: 79, attempts: 892 },
  { subject: "Physics", avgScore: 75, attempts: 834 },
]
